# Generated by Django 5.2.5 on 2025-09-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='honoconta',
            name='meses_credito',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
