# Generated by Django 5.2.5 on 2025-09-12 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_activo'),
        ('contable', '0002_honoconta_meses_credito'),
        ('core', '0002_rol_auditoria_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='VencimientoConta',
            fields=[
                ('timestampedusermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedusermodel')),
                ('tipo_documento', models.CharField(choices=[('IVA', 'IVA'), ('REN', 'Renta'), ('ANT', 'Anticipos'), ('FAC', 'Facilidad'), ('IPS', 'IPS')], max_length=10)),
                ('fecha_vencimiento', models.DateField()),
                ('notificado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            bases=('core.timestampedusermodel',),
        ),
    ]
