# Generated by Django 5.2.5 on 2025-09-04 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_options'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocJuri',
            fields=[
                ('timestampedusermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedusermodel')),
                ('titulo', models.CharField(max_length=150)),
                ('archivo_pdf', models.FileField(upload_to='documentos/juridico/')),
                ('estado', models.CharField(choices=[('REC', 'Recibido'), ('ARC', 'En Archivo'), ('DEV', 'Devuelto')], default='REC', max_length=3)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            bases=('core.timestampedusermodel',),
        ),
        migrations.CreateModel(
            name='GestioJuri',
            fields=[
                ('timestampedusermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedusermodel')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            bases=('core.timestampedusermodel',),
        ),
        migrations.CreateModel(
            name='HonoJuri',
            fields=[
                ('timestampedusermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedusermodel')),
                ('concepto', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('modalidad', models.CharField(choices=[('CONT', 'Contado'), ('CRED', 'Crédito')], default='CONT', max_length=4)),
                ('periodo', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            bases=('core.timestampedusermodel',),
        ),
    ]
