# Generated by Django 5.2.5 on 2025-09-05 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_options'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('timestampedusermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedusermodel')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('abierta', models.BooleanField(default=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            bases=('core.timestampedusermodel',),
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('timestampedusermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedusermodel')),
                ('tipo', models.CharField(choices=[('ING', 'Ingreso'), ('EGR', 'Egreso')], max_length=3)),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('modalidad', models.CharField(choices=[('CONT', 'Contado'), ('CRED', 'Crédito')], max_length=10)),
                ('caja_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.caja')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            bases=('core.timestampedusermodel',),
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('timestampedusermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedusermodel')),
                ('detalle', models.TextField(blank=True, null=True)),
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recibo', to='caja.movimientocaja')),
            ],
            bases=('core.timestampedusermodel',),
        ),
    ]
