# Generated by Django 5.2.5 on 2025-09-06 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_movimientocaja_usuario_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
