# Generated by Django 5.2.5 on 2025-09-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_movimientocaja_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='numero_referencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='tipo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=15),
        ),
    ]
