# Generated by Django 5.2.5 on 2025-09-18 17:50

from django.db import migrations

def asignar_admin(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Caja = apps.get_model("caja", "Caja")
    try:
        admin = User.objects.get(username="admin")
    except User.DoesNotExist:
        return  # si no existe admin, no hace nada
    for caja in Caja.objects.filter(creado_por__isnull=True):
        caja.creado_por = admin
        caja.save()


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_movimientocaja_numero_referencia_and_more'),
    ]

    operations = [
        migrations.RunPython(asignar_admin),
    ]
